/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BarcodeTypes } from "./components/bar-code/types";
export namespace Components {
    interface BarCode {
        /**
          * Barcode type
         */
        "barcode": BarcodeTypes;
        /**
          * Text
         */
        "text": string;
    }
}
declare global {
    interface HTMLBarCodeElement extends Components.BarCode, HTMLStencilElement {
    }
    var HTMLBarCodeElement: {
        prototype: HTMLBarCodeElement;
        new (): HTMLBarCodeElement;
    };
    interface HTMLElementTagNameMap {
        "bar-code": HTMLBarCodeElement;
    }
}
declare namespace LocalJSX {
    interface BarCode {
        /**
          * Barcode type
         */
        "barcode"?: BarcodeTypes;
        /**
          * Text
         */
        "text"?: string;
    }
    interface IntrinsicElements {
        "bar-code": BarCode;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bar-code": LocalJSX.BarCode & JSXBase.HTMLAttributes<HTMLBarCodeElement>;
        }
    }
}
